Controllers/BoloCaseiroController.cs
using Microsoft.AspNetCore.Mvc;

namespace TelmaBolossite.Controllers
{
    public class BoloCaseiroController : Controller
    {
        private readonly Contexto db;

        public BoloCaseiroController(Contexto _db)
        {
            db = _db;
        }

        public IActionResult BoloCaseiro()
        {
            return View();
        }
    }
}

Controllers/BoloDeFestaController.cs
using Microsoft.AspNetCore.Mvc;

namespace TelmaBolossite.Controllers
{
    public class BoloDeFestaController : Controller
    {
        public IActionResult BolodeFesta()
        {
            return View();
        }
    }
}

Controllers/BoloDePoteController.cs
using Microsoft.AspNetCore.Mvc;

namespace TelmaBolossite.Controllers
{
    public class BoloDePoteController : Controller
    {
        public IActionResult BoloDePote()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TelmaBolossite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <!--link css-->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   

    <title>Telma Bolos</title>
    <link rel="icon" href="~/img/logo.png" type="image" width="32" height="32">
</head>
<body>
    <header>
        <div class="menu">
            <div class="header-logo">
                <img src="~/img/logotipo.png" alt="">
            </div>
            <div class="header-menu">
                <a asp-controller="Home" asp-action="Index">Home</a>
                <a asp-controller="BoloDeFesta" asp-action="BoloDeFesta">Bolo de Festa</a>
                <a asp-controller="BoloCaseiro" asp-action="BoloCaseiro">Bolo Caseiro</a>
                <a asp-controller="BoloDePote" asp-action="BoloDePote">Bolo de Pote</a>
            </div>
            <div class="header-login">
                <a asp-controller="Login" asp-action="Login" class="btn-login">Login</a>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ---------------------------- FOOTER ----------------------------  -->

    <footer>
        <div class="footer-info">
            <div class="col-info funcionamento">
                <h3>Funcionamento</h3>
                <p>Segunda à Sábado: <br> 09:00 às 18:00</p>
                <p>Domingos: <br> 08:00 às 11:00</p>
            </div>
            <div class="col-info localizacao">
                <h3>Localização</h3>
                <p>Rua 24 de Outubro, Nº269, <br> Centro, Taquaritinga-SP</p>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3714.5278839961366!2d-48.51180140637675!3d-21.408486443229542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94b93971c5482919%3A0x8a3881d8503fe597!2sR.%20Vinte%20e%20Quatro%20de%20Outubro%2C%20269%20-%20Taquaritinga%2C%20SP%2C%2015900-000!5e0!3m2!1spt-BR!2sbr!4v1696379064446!5m2!1spt-BR!2sbr" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="col-info sobre">
                <h3>Sobre nossa confeitaria</h3>
                <p>A Telma Bolos Confeitaria nasceu há 7 anos da experiência da confeiteira Telma. Há algumas gerações, a família Telma Bolos vem construindo uma maneira diferente de encantar seus clientes.</p>
            </div>
            <div class="col-info sociais">
                <h3>Nossas redes sociais</h3>
                <a href="https://instagram.com/telmabolos_ofc?igshid=MmVlMjlkMTBhMg==" class="social-link" target="_blank">
                    <img src="~/img/instagram-color.png" />
                </a>
                <a href="https://api.whatsapp.com/send?phone=5516992848562&text=Ol%C3%A1%20Telma,%20gostaria%20de%20fazer%20uma%20encomenda!" class="social-link" target="_blank">
                    <img src="~/img/whatsapp1.png" />
                </a>
                <a href="https://www.facebook.com/TelmaAlvesBolos?mibextid=LQQJ4d" class="social-link" target="_blank">
                    <img src="~/img/facebook1.png"/>
                </a>
            </div>
        </div>
    </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/app.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>