Controllers/BoloDeFestaController.cs
using Microsoft.AspNetCore.Mvc;

namespace TelmaBolossite.Controllers
{
    public class BoloDeFestaController : Controller
    {
        public IActionResult BolodeFesta()
        {
            return View();
        }
    }
}

Controllers/CarrinhoController.cs
using Microsoft.AspNetCore.Mvc;

namespace TelmaBolossite.Controllers
{
    public class CarrinhoController : Controller
    {
        public IActionResult Carrinho()
        {
            return View();
        }

        public IActionResult Finalizado()
        {
            return View();
        }
    }
}

Views/BoloDeFesta/BolodeFesta.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="~/css/BoloFesta.css" />

<div class="toolbar">
    <h1 class="brand">Bolos de Festa:</h1>
    <br>
    <p>
        <a asp-controller="Carrinho" asp-action="Carrinho">
            Itens no Carrinho:
            <span id="count">0</span>, Total:
            <span id="sum">0</span>
        </a>
    </p>
</div>


<div class="products">
    <div class="product">
        <h3>Bolo 1 Receita</h3>
        <p class="img-bolo">
            <img  src="~/img/boloflores.png" />Valor: R$230,00
        </p>
        <p class="descricao_bolo">
            Recheio e massa disponível a pronta entrega:
        <p class="recheiobolo">
            Recheio: Brigadeiro com Doce de leite
            Massa: Massa de chocolate
        </p>
        <button data-id="2" data-price="230.00" data-title="Bolo 1 Receita">Adicionar ao carrinho</button>
    </div>

    <div class="product">
        <h3>Bolo 1/2 Receita</h3>
        <p class="img-bolo">
            <img src="~/img/bolomaracuja.png" />Valor: R$ 180,00
           <p class="descricao_bolo">
            Recheio e massa disponível a pronta entrega:
            <p class="recheiobolo">
            Recheio: Ninho com Morango
            Massa: Massa branca
            </p>

        <button data-id="4" data-price="180.00" data-title="Bolo 1/2 Receita">Adicionar no carrinho</button>
    </div>

    <div class="product">
        <h3>Bolo 1/4 (24 Fatias)</h3>
        <p class="img-bolo">
            <img  src="~/img/bolobranco.png" />Valor: R$140,00
        </p>
        <p class="descricao_bolo">
            Recheio e massa disponível a pronta entrega:
        <p class="recheiobolo">
            Recheio: Bombom de Morango
            Massa: Massa de chocolate
        </p>
        <button data-id="1" data-price="140.00" data-title="Bolo 1/2 Receita">Adicionar ao carrinho</button>
    </div>


    <div class="product">
        <h3>Bolo 15 Fatias</h3>
        <p class="img-bolo">
            <img  src="~/img/bolosonic.jpeg" />Valor: 100,00
        </p>
        <p class="descricao_bolo">
            Recheio e massa disponível a pronta entrega:
        <p class="recheiobolo">
            Recheio: Ninho com Abacaxi
            Massa: Massa branca
        </p>
        <button data-id="3" data-price="100.00" data-title="Bolo 15 Fatias">Adicionar ao carrinho</button>
    </div>
</div>